In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
df = pd.read_csv("E-commerce Website Logs.csv",na_values=["--"], dtype={"age": "Int64"})
df

,accessed_date,duration_(secs),network_protocol,ip,bytes,accessed_Ffom,age,gender,country,membership,language,sales,returned,returned_amount,pay_method
0,2017-03-14 17:43:57.172,2533,TCP,1.10.195.126,20100,Chrome,28,Female,CA,Normal,English,261.9600,No,0.00,Credit Card
1,2017-03-14 17:43:57.172,4034,TCP,1.1.217.211,20500,Mozilla Firefox,21,Male,AR,Normal,English,731.9400,No,0.00,Debit Card
2,2017-03-14 17:43:26.135,1525,TCP,1.115.198.107,90100,Mozilla Firefox,20,Male,PL,Normal,English,14.6200,No,0.00,Cash
3,2017-03-14 17:43:26.135,4572,TCP,1.121.152.143,100300,Mozilla Firefox,66,Female,IN,Normal,Spanish,957.5775,No,0.00,Credit Card
4,2017-03-14 18:17:09.005,3652,TCP,1.123.135.213,270200,Mozilla Firefox,53,Female,KR,Normal,Spanish,22.3680,No,0.00,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172833,2017-03-16 11:42:01.298,4372,TCP,94.197.121.229,100600,Android App,<NA>,Male,US,Normal,English,0.0000,Yes,143.36,Debit Card
172834,2017-03-16 12:10:17.340,2167,TCP,129.110.241.72,30400,Android App,<NA>,Female,IT,Normal,English,15.1500,No,0.00,Cash
172835,2017-03-16 12:10:17.340,2725,TCP,185.119.252.121,100300,Android App,<NA>,Female,IT,Normal,English,600.1600,No,0.00,Credit Card
172836,2017-03-16 15:52:58.342,3728,TCP,185.145.107.23,50200,Android App,<NA>,Male,US,Normal,Russian,75.7500,No,0.00,Cash
172837,2017-03-16 15:52:58.342,3420,TCP,202.69.12.251,170800,Android App,<NA>,Female,CA,Normal,English,23.4600,No,0.00,Credit Card

In [4]:
# Particionando os dados por data - Parte 1
df['data'] = pd.to_datetime(df["accessed_date"], errors="coerce").dt.date
for data in df['data'].unique():
    df_data = df[df['data'] == data]
    df_data.to_csv(f"dados_brutos\{data}.csv", index=False)

In [14]:
# vistas de lote - Parte 2
def acessar_dados(data, fazer, var, var2 = None):
    df = pd.read_csv(f"dados_brutos\{data}.csv")
    
    if fazer == "filtrar":
        df = df[var]
        df.to_csv(f"vistas_lote\{data}_{var}_filtrado.csv", index=False)

    elif fazer == "media":
        pd.DataFrame({f"media":[df[var].mean()]}).to_csv(f"vistas_lote\{data}_{var}_media.csv", index=False)

    elif fazer == 'contagem':
        pd.DataFrame({f"contagem":[df[var].count()]}).to_csv(f"vistas_lote\{data}_{var}_contagem.csv", index=False)

    elif fazer == 'maximo':
        pd.DataFrame({f"maximo":[df[var].max()]}).to_csv(f"vistas_lote\{data}_{var}_maximo.csv", index=False)

    elif fazer == 'minimo':
        pd.DataFrame({f"minimo":[df[var].min()]}).to_csv(f"vistas_lote\{data}_{var}_minimo.csv", index=False)

    elif fazer == 'mediana':
        pd.DataFrame({f"mediana":[df[var].median()]}).to_csv(f"vistas_lote\{data}_{var}_mediana.csv", index=False)

    elif fazer == 'desvio_padrao':
        pd.DataFrame({f"desvio_padrao":[df[var].std()]}).to_csv(f"vistas_lote\{data}_{var}_desvio_padrao.csv", index=False)

    elif fazer == 'variancia':
        pd.DataFrame({f"variancia":[df[var].var()]}).to_csv(f"vistas_lote\{data}_{var}_variancia.csv", index=False)

    elif fazer == 'moda':
        pd.DataFrame({f"moda":[df[var].mode()[0]]}).to_csv(f"vistas_lote\{data}_{var}_moda.csv", index=False)
        
    elif fazer == 'correlacao':
        if df[var].dtype == "object":
            df = pd.get_dummies(df, columns=[var])

        if df[var2].dtype == "object":
            df = pd.get_dummies(df, columns=[var2])

        # Pega colunas relacionadas
        cols_var = [c for c in df.columns if c == var or c.startswith(var + "_")]
        cols_var2 = [c for c in df.columns if c == var2 or c.startswith(var2 + "_")]

        # Calcula correlação
        corr = df[cols_var + cols_var2].corr().loc[cols_var, cols_var2]
        corr.iloc[0, 0:].to_csv(f"vistas_lote\{data}_{var}_{var2}_correlacao.csv", index=False)
    elif fazer == 'covariancia':
        df_cov = df[[var, var2]].cov().iloc[0,1]
        pd.DataFrame({f"covariancia":[df_cov]}).to_csv(f"vistas_lote\{data}_{var}_{var2}_covariancia.csv", index=False)

    return

In [15]:
acessar_dados("2017-03-15", "correlacao", "age", "gender")

In [7]:
dummy_var2 = pd.get_dummies(df['gender'], prefix='gender')
dummy_var2

        gender_Female  gender_Male  gender_Unknown
0                True        False           False
1               False         True           False
2               False         True           False
3                True        False           False
4                True        False           False
...               ...          ...             ...
172833          False         True           False
172834           True        False           False
172835           True        False           False
172836          False         True           False
172837           True        False           False

[172838 rows x 3 columns]